# Generated by Django 3.1.5 on 2021-01-16 20:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodationApp', '0003_auto_20210115_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroom',
            name='description',
            field=models.TextField(max_length=1023),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='roomNumber',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewText',
            field=models.CharField(max_length=1023),
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
