# Generated by Django 3.1.5 on 2021-01-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accomodationApp', '0006_uploadimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImage',
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
